services:
  - type: web
    name: products-crud
    env: docker
    repo: https://github.com/tu-usuario/products-crud
    rootDir: ProductsAPI
    dockerfilePath: ProductsAPI/Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
